<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      My Profile
      <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
      <!-- <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li> -->
      <!-- <li class="active">Here</li> -->
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
              <!-- Widget: user widget style 1 -->
              <div class="box box-widget widget-user-2">
                <!-- Add the bg color to the header using any of the bg-* classes -->
                <div class="widget-user-header bg-yellow">
                  <div class="widget-user-image">
                    <img alt="User Avatar" src="assets/template/dist/img/girl.png" class="img-circle">
                  </div><!-- /.widget-user-image -->
                  <h3 class="widget-user-username" style="text-transform:capitalize;"><?php if($this->session->nickname){ echo $this->session->nickname; }else { echo " add nickname"; } ?></h3>
                  <h5 class="widget-user-desc"><?php echo $this->session->email;?></h5>
                </div>
                <div class="box-footer no-padding">
                  <ul class="nav nav-stacked">
                    <li><a href="#">HerGROUP User ID <span class="pull-right badge bg-blue"><?php echo $this->session->userId;?></span></a></li>
                    <li><a href="#">Joined on <span class="pull-right badge bg-aqua"><?php echo date("M-d-Y", strtotime($this->session->joinedOn)); ?></span></a></li>
                    <li><a href="#">Reported crimes <span class="pull-right badge bg-red">0</span></a></li>
                  </ul>
                </div>
              </div><!-- /.widget-user -->
            </div>
              <div class="col-md-4"></div>


              </div>
    <!-- Your Page Content Here -->

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->
