<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
     Report a Crime
      <small>Here you can report a crime</small>
    </h1>
    <ol class="breadcrumb">
      <!-- <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li> -->
      <!-- <li class="active">Here</li> -->
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">

    <div class="row">
      <div class="col-md-8">
      <div id="mapme" style=" height: 500px;">  </div>
    </div>

    <div class="col-md-4">

            <!-- general form elements -->
            <div class="box box-danger">
              <div class="box-header with-border">
                <h3 class="box-title">Provide Details</h3>
              </div><!-- /.box-header -->
              <!-- form start -->
              <!-- <form role="form"> -->
                <div class="box-body">
                  <div class="form-group">

                    <div class="input-group input-group-sm">
                    <input type="text" class="form-control" placeholder="Type any address" id="searchAddress" autofocus="" autocomplete="">
                    <span class="input-group-btn">
                      <button type="button" class="btn btn-info btn-flat" id="getAddress">Go!</button>
                    </span>

                  </div>
                  <!-- <p class="margin">Found: <code> Address </code></p> -->

                  </div>
                  <div class="callout callout-info" style="display:none" id="enterAddressInput" style="display:none">
                   <h4>Search for an address / use the marker to proceed</h4>
                 </div>
                </div><!-- /.box-body -->

              <!-- </form> -->
            </div><!-- /.box -->

            <div class="box box-success" style="display:none" id="foundAddressPane">
              <div class="box-header with-border">
                <h3 class="box-title">Found Address</h3>
              </div><!-- /.box-header -->
              <!-- form start -->
                <div class="box-body">
                  <p id="dynamicAddress"></p>
                  <div style="display:none">
                    <div id="reporterID"><?php echo $this->session->reporterId ?></div>
                    <div id="dynamicLat"></div>
                      <div id="dynamicLng"></div>
                  </div>
                </div><!-- /.box-body -->

            </div><!-- /.box -->


            <div class="box box-primary" style="display:none" id="crimeDescPane">
              <div class="box-header with-border">
                <h3 class="box-title">Enter description</h3>
              </div><!-- /.box-header -->
              <!-- form start -->
                <div class="box-body">
                  <div class="form-group">
                          <textarea placeholder="Enter description..." rows="3" class="form-control" id="cdT"></textarea>
                        </div>
                        <div class="callout callout-danger" style="display:none" id="descriptionTextError" style="display:none">
                         <h4>Cannot submit without description</h4>
                       </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                  <button class="btn btn-danger" id="sendCrimeReport" style="float:right">Submit</button>

            </div><!-- /.box -->



          </div>

          <div class="alert alert-success"  style="display:none" id="reportNotification">
                    <h4>	<i class="icon fa fa-check"></i> Reported!</h4>
                    Your report ID is <span id="repId"><span>. Thank you for reporting !
                  </div>





    </div><!-- /.row -->

  </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<script>
loadReportCrimeMap();
console.log("Started loading the Report a crime map...");
</script>
