<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HerGROUP</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="assets/template/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="assets/template/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="assets/template/dist/css/skins/skin-blue.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <!--
  BODY TAG OPTIONS:
  =================
  Apply one or more of the following classes to get the
  desired effect
  |---------------------------------------------------------|
  | SKINS         | skin-blue                               |
  |               | skin-black                              |
  |               | skin-purple                             |
  |               | skin-yellow                             |
  |               | skin-red                                |
  |               | skin-green                              |
  |---------------------------------------------------------|
  |LAYOUT OPTIONS | fixed                                   |
  |               | layout-boxed                            |
  |               | layout-top-nav                          |
  |               | sidebar-collapse                        |
  |               | sidebar-mini                            |
  |---------------------------------------------------------|
  -->
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      <!-- Main Header -->
      <header class="main-header">

        <!-- Logo -->
        <a href="/my-dashboard" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>h</b>G</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Her</b>GROUP</span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                <!-- Menu toggle button -->

                <ul class="dropdown-menu">

                    <!-- inner menu: contains the messages -->
                    <ul class="menu">
                      <li><!-- start message -->
                        <a href="#">
                          <div class="pull-left">
                            <!-- User Image -->
                            <img src="assets/template/dist/img/girl.png" class="img-circle" alt="User Image">
                          </div>
                          <!-- Message title and timestamp -->

                        </a>
                      </li><!-- end message -->
                    </ul><!-- /.menu -->
                  </li>
                  <!-- <li class="footer"><a href="#">See All Messages</a></li> -->
                </ul>
              </li><!-- /.messages-menu -->

              <!-- Notifications Menu -->

              <!-- Tasks Menu -->

              <!-- User Account Menu -->
              <li class="dropdown user user-menu">



                <!-- Menu Toggle Button -->
                <a href="/logout">

                  Logout &nbsp;

                  <span style="color:rgb(202,69,112)"><i class="fa fa-sign-out fa-1x"></i></span>&nbsp;

                  <!-- The user image in the navbar-->
                  <!-- <img src="assets/template/dist/img/girl.png" class="user-image" alt="User Image"> -->
                  <!-- hidden-xs hides the username on small devices so only the image appears. -->
                  <span class="hidden-xs" style="text-transform:capitalize;">  <?php if($this->session->nickname){ echo $this->session->nickname; }else { echo " add nickname"; } ?></span>


                </a>

              </li>
              <!-- Control Sidebar Toggle Button -->
              <!-- <li>
                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
              </li> -->
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

          <!-- Sidebar user panel (optional) -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="assets/template/dist/img/girl.png" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p style="text-transform:capitalize;">    <?php if($this->session->nickname){ echo $this->session->nickname; }else { echo " add nickname"; } ?></p>
              <!-- Status -->
              <!-- <a href="#"><i class="fa fa-circle text-success"></i> Online</a> -->
            </div>
          </div>

          <!-- search form (Optional) -->
          <!-- <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form> -->
          <!-- /.search form -->

          <!-- Sidebar Menu -->
          <ul class="sidebar-menu">
            <!-- <li class="header">Navigation</li> -->
            <!-- Optionally, you can add icons to the links -->
            <li  <?php if ($this->session->currentNav == 'navDash'){ echo 'class="active"';} ?> ><a href="/my-dashboard"><i class="fa fa-th-large" style="color:rgb(202,69,112)"></i> <span>My Dashboard</span></a></li>
            <li  <?php if ($this->session->currentNav == 'navProf'){ echo 'class="active"';} ?> ><a href="/profile"><i class="fa fa-female" style="color:yellow"></i> <span>My Profile</span></a></li>
            <li  <?php if ($this->session->currentNav == 'navRC'){ echo 'class="active"';} ?> ><a href="/report-crime"><i class="fa fa-user-secret"  style="color:red"></i> <span>Report a Crime</span></a></li>
            <li  <?php if ($this->session->currentNav == 'navRCNb'){ echo 'class="active"';} ?> ><a href="/reported-crimes-nearby"><i class="fa fa-taxi"  style="color:blue"></i> <span>Crimes reported near by</span></a></li>
            <!-- <li class="treeview">
              <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="#">Link in level 2</a></li>
                <li><a href="#">Link in level 2</a></li>
              </ul>
            </li> -->
          </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
      </aside>
    </div><!-- ./wrapper -->

      <!-- REQUIRED JS SCRIPTS -->

      <!-- jQuery 2.1.4 -->
      <script src="assets/template/plugins/jQuery/jQuery-2.1.4.min.js"></script>
      <!-- Bootstrap 3.3.5 -->
      <script src="assets/template/bootstrap/js/bootstrap.min.js"></script>
      <!-- AdminLTE App -->
      <script src="assets/template/dist/js/app.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
      <script src="http://l2.io/ip.js?var=myip"></script>
      <!-- <script async defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbzYWCFf-f1dKQiPou874cvSKaFCx1Lf0&callback=initMap">
        </script> -->
        <!-- <script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclusterer/1.0/src/markerclusterer.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
        <script src="/assets/js/gmaps.js"></script> -->

      	<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> -->
      <script src="http://www.geoplugin.net/javascript.gp" type="text/javascript"></script>
      <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBDNfkdLJYi2Sr4dNuhhAZv78ZjE_TPsDk&sensor=false"></script>

      <script src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclusterer/1.0/src/markerclusterer.js"></script>
      <!-- <script src="http://maps.google.com/maps/api/js?sensor=true"></script> -->
      <script src="assets/js/gmaps.js"></script>
      <script src="assets/js/user.js"></script>

      <!-- Optionally, you can add Slimscroll and FastClick plugins.
           Both of these plugins are recommended to enhance the
           user experience. Slimscroll is required when using the
           fixed layout. -->
