
  <div id="pageintro" class="centred clear">
    <!-- ################################################################################################ -->
    <ul class="carousel-items">
      <li>
        <article>
          <p>Welcome to HerGROUP</p>
          <h2 class="heading">Join us and Be safe</h2>
          <p>“A ship in harbor is safe, but that is not what ships are built for.” </p>
          <ul class="nospace inline">
            <li><a class="btn" href="/login">Login</a></li>
            <li><a class="btn " href="/register">Register</a></li>
          </ul>
        </article>
      </li>

    </ul>
    <!-- ################################################################################################ -->
  </div>
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
</div>
<!-- End Top Background Image Wrapper -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->

<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper bgded" style="background-image:url('images/demo/backgrounds/02.png')">
  <section id="featured" class="container clear">
    <!-- ################################################################################################ -->
    <h2 class="center btmspace-50">What is herGroup ?</h2>
    <ul class="nospace group center">
      <li class="one_quarter first">
        <article><a href="#"><i class="fa fa-female btmspace-30"></i></a>
          <h4 class="heading">online safety group</h4>
          <p>Lets be a good online safety group and help eachother</p>
          <p></p>
        </article>
      </li>
      <li class="one_quarter">
        <article><a href="#"><i class="fa fa-user-secret btmspace-30"></i></a>
          <h4 class="heading">report a crime</h4>
          <p>Want to report a crime ? Report it so that we all can stay safe</p>
          <p></p>
        </article>
      </li>
      <li class="one_quarter">
        <article><a href="#"><i class="fa fa-taxi btmspace-30"></i></a>
          <h4 class="heading">reported crimes near by</h4>
          <p>Check reported crimes nearby and stay safe</p>
          <p></p>
        </article>
      </li>
      <li class="one_quarter">
        <article><a href="#"><i class="fa fa-shield btmspace-30"></i></a>
          <h4 class="heading">completely anaonymous</h4>
          <p>You will be here with your own nickname</p>
          <p></p>
        </article>
      </li>
    </ul>
    <!-- ################################################################################################ -->
    <div class="clear"></div>
  </section>
</div>
