
  <div id="pageintro" class="centred clear">
    <!-- ################################################################################################ -->
    <!-- <ul class="carousel-items">
      <li> -->
        <!-- <article> -->
          <section class="login">
  	<div class="titulo">Recover your password</div>
  	<form action="#" method="post" enctype="application/x-www-form-urlencoded">
      	<input type="text" required title="E-Mail ID required" placeholder="E-mail" data-icon="U" id="reqRecovery">
          <div class="olvido">
            <!-- <div class="col"><a href="/login" title="Login to HerGROUP">Login</a></div>
            <div class="col"><a href="/register" title="Register to HerGROUP">Register</a></div> -->
          </div>
          <a href="#" id="recoverMe">Recover</a>
      </form>
  </section>
        <!-- </article> -->
      <!-- </li>

    </ul> -->
    <!-- ################################################################################################ -->
  </div>
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
</div>
<!-- End Top Background Image Wrapper -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->

<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper bgded" style="background-image:url('images/demo/backgrounds/02.png')">
  <section id="featured" class="container clear">
    <!-- ################################################################################################ -->
    <h2 class="center btmspace-50">What is herGroup ?</h2>
    <ul class="nospace group center">
      <li class="one_quarter first">
        <article><a href="#"><i class="fa fa-female btmspace-30"></i></a>
          <h4 class="heading">online safety group</h4>
          <p>Lets be a good online safety group and help eachother</p>
          <p></p>
        </article>
      </li>
      <li class="one_quarter">
        <article><a href="#"><i class="fa fa-user-secret btmspace-30"></i></a>
          <h4 class="heading">report a crime</h4>
          <p>Want to report a crime ? Report it so that we all can stay safe</p>
          <p></p>
        </article>
      </li>
      <li class="one_quarter">
        <article><a href="#"><i class="fa fa-taxi btmspace-30"></i></a>
          <h4 class="heading">reported crimes near by</h4>
          <p>Check reported crimes nearby and stay safe</p>
          <p></p>
        </article>
      </li>
      <li class="one_quarter">
        <article><a href="#"><i class="fa fa-shield btmspace-30"></i></a>
          <h4 class="heading">completely anaonymous</h4>
          <p>You will be here with your own nickname</p>
          <p></p>
        </article>
      </li>
    </ul>
    <!-- ################################################################################################ -->
    <div class="clear"></div>
  </section>
</div>
