
  <div id="pageintro" class="centred clear">
    <!-- ################################################################################################ -->
    <!-- <ul class="carousel-items">
      <li> -->
        <!-- <article> -->
<section class="login">
  	<div class="titulo">Member Registration</div>
  	<!-- <form id="registerform" method="post" enctype="application/x-www-form-urlencoded">
      	<input type="text" id="email" required title="Email required" placeholder="E-mail" data-icon="U">
          <input type="password" id="password" required title="Password required" placeholder="Password" data-icon="x">
          <div class="olvido">
          	<div class="col"><a href="/login" title="Login to HerGROUP">Already Registered</a></div>
              <div class="col"><a href="/recover" title="Recover your password">Forgot Password</a></div>
          </div>

      </form> -->

      <form  id="regform" enctype="application/x-www-form-urlencoded">
          <input type="text"  id="regemail" name="inputEmail" required title="Please enter your E-mail" placeholder="E-mail" data-icon="U" autofocus autocomplete="off">
            <input type="password" id="regpassword" name="inputPWD" required title="Please choose a Password" placeholder="Password" data-icon="x">
            <div class="olvido">
              <div class="col" id="alreadyregisterD"><a href="/login" title="Login to HerGROUP">Already Registered</a></div>
                <div class="col"  id="forgotP"><a href="/recover" title="Recover your password">Forgot Password</a></div>
                <div id="alreadyexits" style="display:none"><a title="Please try again">E-mail already exits</a></div>
                <div id="registerDone" style="display:none"><a title="Please verify account">We have sent you verification E-Mail.</a></div>
            </div>
            <a href="#" type="submit" id="register" >Register</a>
            <a  type="submit" id="verifyEmail" style="display:none" >Please verify your E-mail</a>
        </form>
  </section>
        <!-- </article> -->
      <!-- </li>

    </ul> -->
    <!-- ################################################################################################ -->
  </div>
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
</div>
<!-- End Top Background Image Wrapper -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->

<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper bgded" style="background-image:url('images/demo/backgrounds/02.png')">
  <section id="featured" class="container clear">
    <!-- ################################################################################################ -->
    <h2 class="center btmspace-50">What is herGroup ?</h2>
    <ul class="nospace group center">
      <li class="one_quarter first">
        <article><a href="#"><i class="fa fa-female btmspace-30"></i></a>
          <h4 class="heading">online safety group</h4>
          <p>Lets be a good online safety group and help eachother</p>
          <p></p>
        </article>
      </li>
      <li class="one_quarter">
        <article><a href="#"><i class="fa fa-user-secret btmspace-30"></i></a>
          <h4 class="heading">report a crime</h4>
          <p>Want to report a crime ? Report it so that we all can stay safe</p>
          <p></p>
        </article>
      </li>
      <li class="one_quarter">
        <article><a href="#"><i class="fa fa-taxi btmspace-30"></i></a>
          <h4 class="heading">reported crimes near by</h4>
          <p>Check reported crimes nearby and stay safe</p>
          <p></p>
        </article>
      </li>
      <li class="one_quarter">
        <article><a href="#"><i class="fa fa-shield btmspace-30"></i></a>
          <h4 class="heading">completely anaonymous</h4>
          <p>You will be here with your own nickname</p>
          <p></p>
        </article>
      </li>
    </ul>
    <!-- ################################################################################################ -->
    <div class="clear"></div>
  </section>
</div>
